language: java
sudo: false
matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=nsis
    - jdk: oraclejdk8
      env: TARGET=makeself
    - os: osx
      osx_image: xcode8.2
      env: TARGET=pkgbuild
addons:
    apt:
        packages:
            - makeself
            - nsis
before_script:
    - sw_vers -productVersion && brew update && brew install ant; ant -version
script: _SILENT_JAVA_OPTIONS="${_JAVA_OPTIONS}"; unset _JAVA_OPTIONS; ant $TARGET; cat out/build/windows-packager.nsi
